
---
title: "An치lisis del cambio en egresados 2020-2021-2023"
author: "Mauricio Medina"
date: "2025-06-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

## 游늵 Datos de egresados

```{r}
egresados <- data.frame(
  A침o = c(2020, 2021, 2023),
  Total = c(139182, 142826, 139182)
)

egresados
```

## 游늳 C치lculo de cambios entre a침os

```{r}
egresados$Cambio_Absoluto <- c(NA, diff(egresados$Total))
egresados$Cambio_Porcentaje <- c(NA, round((diff(egresados$Total) / head(egresados$Total, -1)) * 100, 2))

egresados
```

## 游늵 Gr치fico comparativo de egresados

```{r}
ggplot(egresados, aes(x = factor(A침o), y = Total, fill = factor(A침o))) +
  geom_bar(stat = "identity", width = 0.6) +
  labs(title = "Comparaci칩n del total de egresados por a침o",
       x = "A침o",
       y = "Total de egresados") +
  theme_minimal() +
  theme(legend.position = "none") +
  geom_text(aes(label = Total), vjust = -0.5)
```

## 游 Interpretaci칩n

```{r results='asis', echo=FALSE}
cat("### An치lisis del cambio en el n칰mero total de egresados\n\n")

cat(paste0("Entre 2020 y 2021, el total de egresados pas칩 de ", egresados$Total[1],
           " a ", egresados$Total[2],
           ", lo que representa un aumento de ", egresados$Cambio_Absoluto[2],
           " egresados (", egresados$Cambio_Porcentaje[2], "%).\n\n"))

cat(paste0("Entre 2021 y 2023, el total de egresados pas칩 de ", egresados$Total[2],
           " a ", egresados$Total[3],
           ", lo que representa una disminuci칩n de ", abs(egresados$Cambio_Absoluto[3]),
           " egresados (", egresados$Cambio_Porcentaje[3], "%).\n\n"))

cat("En resumen, el gr치fico de barras nos permite visualizar claramente que el a침o 2021 fue el de mayor cantidad de egresados, mientras que en 2020 y 2023 el n칰mero total fue exactamente el mismo. Esta oscilaci칩n puede reflejar variaciones en cohortes, pol칤ticas educativas o condiciones externas como la pandemia.\n")
```
